Repository GIST-Petition-Site-Project/GIST-petition-web, pull requests merged in 2021-07, with the labels that each got.

#2 pr test (#1)
  jsconfig.json
  src/pages/Main/Main.js
Labels: 테스트

#15 feat: 글 목록 페이지 구현 (#4)
  .eslintrc
  jsconfig.json
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/atoms/FilterButton/FilterButton.js
  src/components/atoms/FilterDropDown/FilterDropDown.js
  src/components/atoms/LoadingText/LoadingText.js
  src/components/atoms/PageNumber/PageNumber.css
  src/components/atoms/PageNumber/PageNumber.js
  src/components/atoms/PostListText/PostListText.css
  src/components/atoms/PostListText/PostListText.js
  src/components/atoms/Subject/Subject.js
  src/components/molecules/FilterAnswer/FilterAnswer.js
  src/components/molecules/FilterDropDowns/FilterDropDowns.css
  src/components/molecules/FilterDropDowns/FilterDropDowns.js
  src/components/molecules/Pagination/Pagination.css
  src/components/molecules/Pagination/Pagination.js
  src/components/molecules/Post/Post.css
  src/components/molecules/Post/Post.js
  src/components/molecules/PostListInfo/PostListInfo.js
  src/components/organisms/Posts/Posts.css
  src/components/organisms/Posts/Posts.js
  src/pages/PostList/PostList.css
  src/pages/PostList/PostList.js
  yarn.lock
Labels: 기능

#18 feat: 주의사항 구현 (#13)
  hardcording/주의사항/precaution.css
  hardcording/주의사항/precaution.html
  src/precaution/precaution.css
  src/precaution/precaution.html
Labels: 기능, 리뷰

#20 feat: 글 상세 페이지 구현 (#17)
  package.json
  src/App.js
  src/components/atoms/Button/index.jsx
  src/components/atoms/Input/index.jsx
  src/components/atoms/ListText/ListText.js
  src/components/atoms/PostListText/PostListText.css
  src/components/atoms/PostListText/PostListText.js
  src/components/molecules/Comment.js
  src/components/molecules/Post/Post.js
  src/components/molecules/PostListInfo/PostListInfo.js
  src/components/organisms/CommentList.js
  src/pages/PostView/PostView.js
  yarn.lock
Labels: 기능, 리뷰

#19 feat: 메인 페이지 헤더 구현
  hardcording/header.html
Labels: 기능

#25 feat: 나의 청원 페이지 구현 (#23)
  src/App.js
  src/components/hardcording/MainHeader/MainHeader.css
  src/components/hardcording/MainHeader/MainHeader.js
  src/pages/MyPage/MyPage.js
  src/pages/PostView/PostView.js
Labels: 기능

#31 feat:로그인 페이지 구현(#5)
  src/components/atoms/InternalLink/InternalLink.js
  src/components/atoms/LoginInput/LoginInput.js
  src/components/atoms/RequiredInput/RequiredInput.js
  src/components/atoms/SubTitle/SubTitle.js
  src/components/atoms/SubmitButton/SubmitButton.js
  src/components/atoms/Title/Title.js
  src/components/molecules/InputButtonPair/InputButtonPair.js
  src/components/molecules/InputPair/InputPair.js
  src/components/molecules/TitleBlock/TitleBlock.js
  src/pages/Login/Login.js
Labels: 기능, 리뷰

#37 feat:회원가입 페이지 구현(#6)
  src/components/atoms/RequiredInput/RequiredInput.js
  src/components/molecules/InputButtonPair/InputButtonPair.js
  src/pages/Login/Login.js
  src/pages/SignUp/SignUp.js
Labels: 기능, 리뷰

#38 feat:아이디/비밀번호 찾기 페이지 구현(#7)(#8)
  src/App.js
  src/pages/ForgetID/ForgetID.css
  src/pages/ForgetID/ForgetID.js
  src/pages/ForgetPWD/ForgetPWD.css
  src/pages/ForgetPWD/ForgetPWD.js
  src/pages/Login/Login.js
Labels: 기능, 리뷰

#54 feat: 주의사항 구현 (#53)
  src/components/hardcording/Precaution/Precaution.css
  src/components/hardcording/Precaution/Precaution.js
Labels: Priority: Low, Status: To Do, Type: Feature/Document
