Repository GIST-Petition-Site-Project/GIST-petition-web, pull requests merged in 2022-05, with the labels that each got.

#333 refactor: boolean이 아닌 명시된 청원 진행 상황 status 값을 사용합니다
  public/index.html
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/types/petition.d.ts
Labels: ⚙️ 리팩토링

#335 feat: 한/영 지원을 위한 작업 진행
  package.json
  src/components/NavBar/index.tsx
  src/components/NavBar/locale.ts
  src/hooks/useTranslate.ts
  src/pages/Home/MainPetitions/index.tsx
  src/pages/Home/MainPetitions/locale.ts
  src/redux/lang/langSlice.ts
  src/redux/store.ts
  src/types/locale.d.ts
  tsconfig.extend.json
Labels: 💻 개발

#337 feat: 일부 파일 영문 번역 및 footer 내용 변경
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/NavBar/MyMenu/index.tsx
  src/components/NavBar/MyMenu/locale.ts
  src/components/NavBar/MyMenu/styles.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/locale.ts
  src/components/NavBar/styles.ts
  src/components/UserInput/index.tsx
  src/pages/Guide/index.tsx
  src/pages/Guide/styles.ts
  src/pages/Home/Banner/index.tsx
  src/pages/Home/Banner/locale.ts
  src/pages/Home/MainPetitions/index.tsx
  src/pages/Home/MainPetitions/locale.ts
  src/pages/Login/index.tsx
  src/pages/Login/locale.ts
  src/pages/Login/styles.ts
  src/pages/Register/index.tsx
Labels: 🥇 우선순위 - 높음!!, 🎮 기능

#340 feat: MainPrecaution 영문 번역
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/locale.ts
  src/pages/Write/WritePrecaution/locale.ts
Labels: 🥇 우선순위 - 높음!!, 🎮 기능
