Repository GIST-Petition-Site-Project/GIST-petition-web, pull requests merged in 2022-02, with the labels that each got.

#130 feat: 전역 글꼴 pretendard 설정
  public/index.html
  src/App.css
  src/App.tsx
  src/components/Footer/index.tsx
  src/index.css
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Login/index.tsx
  src/style/Global.tsx
Labels: 🚨 중요!!!, 🎨 디자인, 🛠 수정

#131 Design/main 반응형
  src/pages/Home/index.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/Petitions/PetitionList/index.tsx
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/style/theme.ts
Labels: 🎨 디자인

#133 refact: 게시글 필터를 query-string을 이용하는 방식으로 변경
  package.json
  src/pages/Petitions/PaginationButtons/index.tsx
  src/pages/Petitions/PetitionList/index.tsx
  src/pages/Petitions/PetitionList/styles.ts
  src/pages/Petitions/index.tsx
  src/pages/Petitions/styles.ts
  src/redux/store.ts
  src/types/petition.d.ts
  src/utils/api/petitions/getPetitionsByQuery.ts
  yarn.lock
Labels: 💻 개발, 🚨 중요!!!, 🛠 수정, 🎮 기능

#136 Design/home 반응형 추가
  .eslintrc
  .vscode/extensions.json
  .vscode/settings.json
  package.json
  src/assets/img/footer_logo.png
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/NavBar/styles.ts
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Login/styles.ts
  src/style/theme.ts
  yarn.lock
Labels: 💻 개발, 🥇 우선순위 - 높음!!, 🚨 중요!!!, 🎨 디자인

#142 Design/responsive: 모든 청원 페이지네이션 버튼 반응형 및 디테일 수정
  src/pages/Petition/index.tsx
  src/pages/Petition/styles.ts
  src/pages/Petitions/PaginationButtons/index.tsx
  src/pages/Petitions/PaginationButtons/styles.ts
  src/pages/Petitions/PetitionList/index.tsx
  src/pages/Petitions/PetitionList/styles.ts
Labels: 💻 개발, 🎨 디자인

#143 Design/main: 메인 페이지 반응형 작업
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/style/theme.ts
Labels: 🎨 디자인, 🛠 수정

#145 Feat: NavBar 반응형 구현
  src/assets/img/menu_icon.svg
  src/assets/img/new_logo.svg
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
Labels: 💻 개발, 🎮 기능

#146 Design/responsive: 청원 작성 페이지 반응형 & 로그인 페이지 리팩토링
  src/App.tsx
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/Write/PrecautionModal/index.tsx
  src/pages/Write/PrecautionModal/styles.ts
  src/pages/Write/WritePrecaution/index.tsx
  src/pages/Write/WritePrecaution/styles.ts
  src/pages/Write/index.tsx
  src/pages/Write/styles.ts
Labels: ⚙️ 리팩토링, 🎨 디자인, 🛠 수정

#155 feat: 청원 작성 후 작성한 게시글로 이동시키기
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/index.tsx
  src/utils/api/petitions/postCreatePetition.ts
Labels: 🛠 수정, 🎮 기능

#156 feat: 청원 작성 제목과 내용 글자수 제한 기능과 UI 추가
  src/pages/Write/GuideModal/index.tsx
  src/pages/Write/GuideModal/steps.json
  src/pages/Write/GuideModal/styles.ts
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/PostEditor/styles.ts
  src/pages/Write/index.tsx
Labels: 💻 개발, 🎨 디자인, 🎮 기능

#159 fix: 로그아웃 시 새로고침 하기
  src/components/NavBar/index.tsx
  src/pages/Petitions/PaginationButtons/index.tsx
Labels: 👿 버그, 🛠 수정

#161 Feat: 나의 청원 구현
  src/components/NavBar/index.tsx
  src/components/PaginationButtons/index.tsx
  src/components/PaginationButtons/styles.ts
  src/pages/MyPetitions/index.tsx
  src/pages/MyPetitions/styles.ts
  src/pages/Petitions/index.tsx
  src/route/RootRouter.tsx
  src/types/petition.d.ts
  src/utils/api/index.ts
  src/utils/api/petition/getAgreementCount.ts
  src/utils/api/petition/getMyPetitionsByQuery.ts
  src/utils/api/petition/getPetitionById.ts
  src/utils/api/petition/getPetitionCount.ts
  src/utils/api/petition/getPetitionsByQuery.ts
  src/utils/api/petition/getStateOfAgreement.ts
  src/utils/api/petition/postAgreePetition.ts
  src/utils/api/petition/postCreatePetition.ts
Labels: 💻 개발, ⚙️ 리팩토링, 🎮 기능

#166 design: 모바일용 NavBar 디자인 변경
  src/components/NavBar/MyMenu/index.tsx
  src/components/NavBar/MyMenu/styles.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
Labels: ⚙️ 리팩토링, 🎨 디자인, 🛠 수정

#175 design: 메인페이지 청원 삭제/숨김/답변 어려움 안내 바 패딩값 주기
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/styles.ts
Labels: 🎨 디자인, 🛠 수정

#177 refactor: API 리턴값 response로 통일
  src/components/PaginationButtons/index.tsx
  src/components/PetitionList/index.tsx
  src/pages/Home/index.tsx
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/Petition/AgreementForm/index.tsx
  src/pages/Petition/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/index.tsx
  src/pages/Register/index.tsx
  src/pages/Write/PostEditor/index.tsx
  src/types/petition.d.ts
  src/utils/api/index.ts
  src/utils/api/petition/getAgreementCount.ts
  src/utils/api/petition/getAgreements.ts
  src/utils/api/petition/getMyPetitionsByQuery.ts
  src/utils/api/petition/getPetitionById.ts
  src/utils/api/petition/getPetitionCount.ts
  src/utils/api/petition/getPetitionsByQuery.ts
  src/utils/api/petition/getStateOfAgreement.ts
  src/utils/api/petition/postAgreePetition.ts
  src/utils/api/user/postDelete.ts
Labels: ⚙️ 리팩토링, 🛠 수정

#182 feat: 사전 동의중인 청원
  src/pages/Petition/AgreementForm/index.tsx
  src/pages/Petition/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/PetitionContents/styles.ts
  src/pages/Petition/index.tsx
  src/route/RootRouter.tsx
  src/utils/api/answer/getRetrieveAnswer.ts
  src/utils/api/comment/getComments.ts
  src/utils/api/comment/postCreateComment.ts
  src/utils/api/index.ts
  src/utils/api/petition/getAgreementCount.ts
  src/utils/api/petition/getAgreements.ts
  src/utils/api/petition/getPetitionById.ts
  src/utils/api/petition/getStateOfAgreement.ts
  src/utils/api/petition/postAgreePetition.ts
Labels: 🎮 기능

#188 feat: 청원 게시글 URL 복사, 공유하기 버튼 추가
  .github/workflows/dev-CD.yaml
  package.json
  public/index.html
  src/pages/Login/index.tsx
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/MyPetitions/index.tsx
  src/pages/Petition/AgreementForm/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/index.tsx
  src/pages/Petition/styles.ts
  src/types/petition.d.ts
Labels: 💻 개발, 🎨 디자인, 🎮 기능

#195 design: 모바일 메뉴 구분선 추가
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
Labels: 🎨 디자인

#197 design: footer 패딩값 적용 & Inner를 Component로 분리
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/components/Inner/index.tsx
  src/components/Inner/styles.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
  src/components/PetitionList/styles.ts
  src/pages/AnsweredPetitions/index.tsx
  src/pages/AnsweredPetitions/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/MyPetitions/index.tsx
  src/pages/MyPetitions/styles.ts
  src/pages/Petition/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/styles.ts
  src/pages/Petition/index.tsx
  src/pages/Petition/styles.ts
  src/pages/Petitions/index.tsx
  src/pages/Petitions/styles.ts
  src/pages/Write/index.tsx
  src/pages/Write/styles.ts
  src/style/theme.ts
Labels: ⚙️ 리팩토링, 🎨 디자인, 🛠 수정, 🗂 스타일

#198 fix: 나의 청원 페이지 - tempUrl로 게시글들 보여주기
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/Petition/AgreementForm/index.tsx
  src/pages/Petition/index.tsx
  src/types/petition.d.ts
  src/utils/api/petition/getStateOfAgreement.ts
Labels: 👿 버그, 🛠 수정, 🎮 기능

#201 Refact: 회원가입 페이지
  src/pages/Register/TermsOfUse/index.tsx
  src/pages/Register/TermsOfUse/styles.ts
  src/pages/Register/index.tsx
  src/redux/register/registerSlice.ts
  src/redux/store.ts
  src/utils/api/user/postRegister.ts
  src/utils/api/user/userDelete.ts
  src/utils/api/verification/postConfirmVerificationCode.ts
  src/utils/api/verification/postCreateVerificationCode.ts
Labels: ⚙️ 리팩토링

#209 feat: 비밀번호 찾기 페이지 추가
  src/pages/FindingPassword/index.tsx
  src/pages/FindingPassword/styles.ts
  src/redux/findPassword/findPasswordSlice.ts
  src/redux/store.ts
  src/route/RootRouter.tsx
  src/types/user.d.ts
  src/utils/api/findPassword/postConfirmVerificationCodeForPassword.ts
  src/utils/api/findPassword/postCreateVerificationCodeForPassword.ts
  src/utils/api/findPassword/putResetPassword.ts
  src/utils/api/index.ts
Labels: 💻 개발, 🎮 기능

#210 Fix: 회원가입 페이지 에러
  src/pages/Register/TermsOfUse/index.tsx
  src/pages/Register/index.tsx
Labels: 👿 버그, 💻 개발

#215 design & refactor: 로그인 페이지 반응형 & 렌더 줄이기
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/types/user.d.ts
  src/utils/checkUser.ts
Labels: 🙋🏻 제안, ⚙️ 리팩토링, 🎨 디자인

#219 feat: 모든 청원 추천순 필터 적용 & UI 피드백 반영
  src/components/NavBar/styles.ts
  src/components/PetitionList/index.tsx
  src/components/PetitionList/styles.ts
  src/pages/Petition/styles.ts
  src/pages/Petitions/index.tsx
  src/pages/Petitions/styles.ts
  src/pages/Write/index.tsx
  src/pages/Write/styles.ts
  src/redux/query/querySlice.ts
  src/types/petition.d.ts
  src/utils/api/index.ts
  src/utils/api/petition/getExpiredPetitionsByQuery.ts
  src/utils/api/petition/getMyPetitionsByQuery.ts
  src/utils/api/petition/getPetitionsByQuery.ts
Labels: 💻 개발, 🎨 디자인, 🎮 기능

#226 fix/warning: NotFound 워닝 & 로그인 400에러 해결
  src/pages/Login/index.tsx
  src/pages/NotFound/index.tsx
  src/types/user.d.ts
Labels: 👿 버그, 🛠 수정

#227 feat: 없는 청원 게시글 조회시 메세지 표시해주기
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petitions/index.tsx
  src/pages/Petitions/styles.ts
  src/types/petition.d.ts
Labels: 🎨 디자인, 🎮 기능

#237 Refact/회원가입 페이지 컴포넌트로 쪼개기
  src/components/LoadingSpinner/index.tsx
  src/components/Register/Accordion/index.tsx
  src/components/Register/Accordion/styles.ts
  src/components/Register/TermOfUseList/index.tsx
  src/components/Register/TermOfUseList/styles.ts
  src/components/UserInput/index.tsx
  src/components/UserInput/styles.ts
  src/pages/Register/TermsOfUse/index.tsx
  src/pages/Register/TermsOfUse/styles.ts
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/redux/register/registerSlice.ts
  src/types/user.d.ts
Labels: 💻 개발, ⚙️ 리팩토링

#238 design: 비밀번호 찾기 input 아이콘 & 내정보 UI 변경
  src/components/Footer/styles.ts
  src/components/NavBar/MyMenu/index.tsx
  src/components/NavBar/MyMenu/styles.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
  src/components/PaginationButtons/index.tsx
  src/components/PaginationButtons/styles.ts
  src/components/PetitionList/index.tsx
  src/components/PetitionList/styles.ts
  src/pages/AnsweredPetitions/index.tsx
  src/pages/AnsweredPetitions/styles.ts
  src/pages/FindingPassword/index.tsx
  src/pages/FindingPassword/styles.ts
  src/pages/Login/index.tsx
  src/pages/Login/styles.ts
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/MyPetitions/MyPetitionList/styles.ts
  src/pages/MyPetitions/index.tsx
  src/pages/MyPetitions/styles.ts
  src/pages/Petitions/index.tsx
  src/style/theme.ts
Labels: 🎨 디자인

#245 refact/ 회원가입 컴포넌트화
  src/components/LoadingSpinner/index.tsx
  src/components/UserInput/index.tsx
  src/components/UserInput/styles.ts
  src/pages/Register/Accordion/index.tsx
  src/pages/Register/Accordion/styles.ts
  src/pages/Register/TermsOfUse/TermOfUseList/index.tsx
  src/pages/Register/TermsOfUse/TermOfUseList/styles.ts
  src/pages/Register/TermsOfUse/index.tsx
  src/pages/Register/TermsOfUse/styles.ts
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/redux/register/registerSlice.ts
  src/redux/store.ts
  src/types/user.d.ts
Labels: 💻 개발, ⚙️ 리팩토링

#247 feat: Agreement 페이지네이션 구현
  src/components/PaginationButtons/index.tsx
  src/pages/Petition/AgreementList/index.tsx
  src/pages/Petition/AgreementList/styles.ts
  src/pages/Petition/PetitionContents/AgreementForm/index.tsx
  src/pages/Petition/PetitionContents/AgreementForm/styles.ts
  src/pages/Petition/PetitionContents/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/AgreementList/styles.ts
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petitions/index.tsx
  src/types/petition.d.ts
  src/utils/api/petitionAPI.ts
Labels: 💻 개발, 🎨 디자인, 🎮 기능

#249 fix: 회원 약관 버튼 오류 해결
  src/pages/Register/Accordion/index.tsx
  src/pages/Register/TermsOfUse/TermOfUseList/index.tsx
  src/pages/Register/TermsOfUse/index.tsx
  src/pages/Register/index.tsx
  src/redux/register/registerSlice.ts
  src/types/user.d.ts
Labels: 👿 버그, 💻 개발

#254 fix: Chakra Button box-shadow 없애기 & 만료된 청원 필터 적용 안되던 문제 해결
  src/components/PaginationButtons/styles.ts
  src/pages/FindingPassword/styles.ts
  src/pages/Petition/PetitionContents/AgreementList/styles.ts
  src/pages/Petitions/index.tsx
  src/utils/api/petitionAPI.ts
Labels: 👿 버그, 🎨 디자인, 🛠 수정

#252 비밀번호 찾기 페이지 컴포넌트로 재구성
  src/components/UserInput/index.tsx
  src/pages/FindingPassword/index.tsx
  src/pages/Register/index.tsx
  src/redux/findPassword/findPasswordSlice.ts
Labels: 💻 개발, ⚙️ 리팩토링

#259 design/main: 메인 UI 변경
  src/assets/img/main2.png
  src/assets/img/menu_icon.svg
  src/assets/img/new_logo_black.svg
  src/components/NavBar/MyMenu/styles.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
  src/pages/AnsweredPetitions/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/MyPetitions/MyPetitionList/styles.ts
  src/pages/MyPetitions/styles.ts
  src/pages/Petitions/styles.ts
Labels: 🙋🏻 제안, 🥈 우선순위 - 중간, 🎨 디자인, 🛠 수정

#261 design/main: main Precaution 순수 css로 구현
  src/components/NavBar/styles.ts
  src/pages/Home/Banner/index.tsx
  src/pages/Home/Banner/styles.ts
  src/pages/Home/MainPetitions/index.tsx
  src/pages/Home/MainPetitions/styles.ts
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/styles.ts
  src/pages/Home/index.tsx
  src/pages/Home/styles.ts
  src/pages/Petitions/index.tsx
  src/pages/Register/index.tsx
  src/style/theme.ts
Labels: 🎨 디자인, 🛠 수정

#258 refact: UserinfoSlice로 합치기
  src/pages/FindingPassword/index.tsx
  src/pages/Login/index.tsx
  src/pages/Register/index.tsx
  src/redux/register/registerSlice.ts
  src/redux/store.ts
  src/redux/userInfo/userInfoSlice.ts
Labels: 💻 개발, ⚙️ 리팩토링

#264 design: 회원 가입 UI 통일 및 회원 약관 추가
  src/components/UserInput/index.tsx
  src/pages/Register/Accordion/index.tsx
  src/pages/Register/Accordion/styles.ts
  src/pages/Register/TermsOfUse/TermOfUseList/styles.ts
  src/pages/Register/TermsOfUse/styles.ts
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
Labels: 🎨 디자인, 🛠 수정

#266 design: 동의하기, 공유하기, 청원 기간, 오픈그래프
  public/index.html
  src/components/PetitionList/index.tsx
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/Petition/PetitionContents/AgreementForm/index.tsx
  src/pages/Petition/PetitionContents/AgreementForm/styles.ts
  src/pages/Petition/PetitionContents/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/AgreementList/styles.ts
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/PetitionContents/styles.ts
  src/pages/Petition/index.tsx
  src/pages/Petition/styles.ts
  src/types/petition.d.ts
  src/utils/getTime.ts
  src/utils/time.ts
Labels: 👿 버그, 🎨 디자인, 🛠 수정, 🎮 기능

#267 feat: 청원 진행 상태 표시
  src/components/UserInput/index.tsx
  src/components/UserInput/styles.ts
  src/pages/ChangePassword/index.tsx
  src/pages/ChangePassword/styles.ts
  src/pages/FindingPassword/index.tsx
  src/pages/FindingPassword/styles.ts
  src/pages/Login/index.tsx
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/MyPetitions/MyPetitionList/styles.ts
  src/pages/Petition/PetitionContents/AgreementList/styles.ts
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/PetitionContents/styles.ts
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/pages/Withdrawal/styles.ts
  src/pages/Write/styles.ts
  src/types/petition.d.ts
Labels: 💻 개발, 🚨 중요!!!, 🎨 디자인, 🎮 기능
