Repository GIST-Petition-Site-Project/GIST-petition-web, pull requests merged in 2022-03, with the labels that each got.

#273 feat: URL 복사 확장성 고려
  public/index.html
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/PetitionContents/styles.ts
  src/pages/Petition/index.tsx
  src/pages/Petition/styles.ts
  src/pages/Write/GuideModal/index.tsx
Labels: ⚙️ 리팩토링, 🗂 스타일, 🎮 기능

#274 회원가입페이지 상태관리 리팩토링
  src/components/NavBar/MyMenu/index.tsx
  src/pages/Register/Email/index.tsx
  src/pages/Register/EmailAndVerification/index.tsx
  src/pages/Register/index.tsx
  src/pages/Withdrawal/index.tsx
  src/redux/userInfo/userInfoSlice.ts
  src/types/user.d.ts
Labels: 💻 개발, ⚙️ 리팩토링

#279 refactor: petition/index.tsx 에서 모든 API 요청 상태 관리
  src/pages/Petition/PetitionContents/AgreementForm/index.tsx
  src/pages/Petition/PetitionContents/AgreementForm/styles.ts
  src/pages/Petition/PetitionContents/AgreementList/index.tsx
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/index.tsx
  src/route/RootRouter.tsx
  src/types/answer.d.ts
  src/types/petition.d.ts
  src/utils/api/petitionAPI.ts
Labels: ⚙️ 리팩토링, 🎮 기능

#280 footer UI 개편
  src/assets/img/footer_logo.png
  src/components/Footer/index.tsx
  src/components/Footer/styles.ts
  src/style/theme.ts
Labels: 💻 개발, 🎨 디자인

#287 feat: 회원 정보 관리 로직 수정
  src/pages/ChangePassword/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/FindPassword/styles.ts
  src/pages/Login/index.tsx
  src/pages/MyInfo/MyInfoitem/index.tsx
  src/pages/MyInfo/MyInfoitem/styles.ts
  src/pages/MyInfo/index.tsx
  src/pages/MyInfo/styles.ts
  src/pages/Register/Email/index.tsx
  src/pages/Register/EmailAndVerification/index.tsx
  src/pages/Register/index.tsx
  src/pages/Withdrawal/index.tsx
  src/route/RootRouter.tsx
Labels: 💻 개발, 🎮 기능

#290 비밀번호 찾기 페이지 리팩토링&userInfoSlice제거
  src/components/Email/index.tsx
  src/components/EmailAndVerification/index.tsx
  src/pages/FindPassword/index.tsx
  src/pages/FindPassword/styles.ts
  src/pages/Register/index.tsx
  src/redux/store.ts
  src/redux/userInfo/userInfoSlice.ts
Labels: 💻 개발, ⚙️ 리팩토링

#292 feat: 이용안내 페이지 제작
  src/components/NavBar/index.tsx
  src/pages/Guide/index.tsx
  src/pages/Guide/styles.ts
  src/pages/Register/TermsOfUse/Accordion/index.tsx
  src/route/RootRouter.tsx
Labels: 🎮 기능

#295 chore:수정된 팀페이지 주소 반영
  src/components/Footer/index.tsx
Labels: 💻 개발

#293 refactor: editor 성능 최적화
  src/pages/Guide/styles.ts
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/PostEditor/styles.ts
Labels: ⚙️ 리팩토링

#299 fix: 네비게이션 로그인 버튼을 눌렀을때도 이전 위치로 돌아가도록 합니다
  src/components/NavBar/MyMenu/index.tsx
  src/components/NavBar/MyMenu/styles.ts
  src/components/NavBar/styles.ts
Labels: 🛠 수정, 🎮 기능

#300 Design/animation
  src/components/PetitionList/index.tsx
  src/components/PetitionList/styles.ts
  src/pages/Home/Banner/styles.ts
  src/pages/MyPetitions/MyPetitionList/index.tsx
  src/pages/MyPetitions/MyPetitionList/styles.ts
  src/pages/Petitions/index.tsx
Labels: 🙋🏻 제안, ⚙️ 리팩토링, 🎨 디자인, 🎮 기능

#302 design: 모바일 뷰 - border 없애기 & 대쉬보드 수직 중앙 정렬
  src/pages/Home/Banner/styles.ts
  src/pages/Petition/styles.ts
  src/pages/Write/styles.ts
Labels: 🎨 디자인, 🛠 수정

#304 feat: answer api 수정 & 카카오톡 공유 제목/글 보이게 설정
  public/index.html
  src/pages/Petition/PetitionContents/index.tsx
  src/pages/Petition/index.tsx
  src/types/petition.d.ts
  src/utils/api/petitionAPI.ts
Labels: 👿 버그, ⚙️ 리팩토링, 🛠 수정, 🎮 기능

#305 fix:회원가입페이지 삭제
  src/pages/MyInfo/index.tsx
  src/route/RootRouter.tsx
Labels: 💻 개발, 🎨 디자인

#308 fix:약관동의 에러메시지 이슈 해결
  src/pages/Register/index.tsx
Labels: 👿 버그, 💻 개발

#296 design: 모바일뷰 select 크기 조정
  src/pages/Login/index.tsx
  src/pages/Petition/PetitionContents/AgreementForm/index.tsx
  src/pages/Petition/PetitionContents/AgreementList/index.tsx
  src/pages/Petitions/index.tsx
  src/pages/Petitions/styles.ts
  src/pages/Register/index.tsx
  src/pages/Withdrawal/index.tsx
  src/route/PrivateRouter.tsx
Labels: ⚙️ 리팩토링, 🎨 디자인

#318 Feat/video 컴포넌트 추가
  src/components/youtube/index.tsx
  src/components/youtube/styles.ts
  src/pages/Petition/PetitionContents/index.tsx
  src/types/answer.d.ts
Labels: 💻 개발, 🎨 디자인, 🎮 기능
