Repository GIST-Petition-Site-Project/GIST-petition-web, pull requests merged in 2022-01, with the labels that each got.

#21 feat:Posts Page 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/containers/Home/Home.tsx
  src/containers/Login/Login.tsx
  src/containers/Posts/Posts.tsx
  src/containers/Posts/posts.json
  tsconfig.json
  yarn.lock
Labels: enhancement

#24 feat:Post Page 퍼블리싱 1
  src/components/MainPrecaution/MainPrecaution.tsx
  src/containers/Posts/Post.tsx
  src/containers/Posts/Posts.tsx
Labels: enhancement

#32 Feat: auth slice 추가
  src/app/rootReducer.ts
  src/app/userSlice.ts
  src/index.tsx
  src/pages/Agreement/Agreement.tsx
  src/pages/Home/Home.tsx
  src/pages/Login/Login.tsx
  src/pages/Login/style.ts
  src/pages/NotFound/NotFound.tsx
  src/pages/Posts/Post.tsx
  src/pages/Posts/Posts.tsx
  src/pages/Posts/posts.json
  src/pages/Register/Register.tsx
  src/pages/Write/Write.tsx
  src/redux/auth/authSlice.ts
  src/redux/store.hooks.ts
  src/redux/store.ts
  src/route/MainRouter.tsx
  src/types/user.d.ts
  src/utils/api/fetchConfigs.ts
  src/utils/api/postLogin.ts
Labels: 개발

#34 Refact/style
  src/pages/Home/Home.tsx
  src/pages/Home/style.ts
  src/pages/Posts/Post.tsx
  src/pages/Posts/Posts.tsx
  src/pages/Posts/style.ts
  src/pages/Register/Register.tsx
  src/pages/Register/style.ts
  src/pages/Write/Write.tsx
  src/pages/Write/style.ts
Labels: 리팩토링

#40 feat: PR시 build 테스트
  .eslintrc
  .github/workflows/dev-CD.yaml
  .github/workflows/dev-CI.yaml
Labels: 개발

#50 Style/post: Post 페이지 컴포넌트 정리
  .github/ISSUE_TEMPLATE/----------.md
  .github/ISSUE_TEMPLATE/-------.md
  src/App.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/MainPrecaution.tsx
  src/pages/Posts/CommentForm/index.tsx
  src/pages/Posts/CommentForm/styles.ts
  src/pages/Posts/CommentList/index.tsx
  src/pages/Posts/PetitionContents/index.tsx
  src/pages/Posts/PetitionContents/styles.ts
  src/pages/Posts/Post.tsx
  src/pages/Posts/posts.json
  src/pages/Posts/style.ts
Labels: 리팩토링, 수정, 스타일

#58 Fix/axios logout
  public/favicon.ico
  src/components/NavBar/NavBar.tsx
  src/utils/api/axiosConfigs.ts
  src/utils/api/getUsersMe.ts
  src/utils/api/postLogin.ts
  src/utils/api/postLogout.ts
  src/utils/api/postRegister.ts
Labels: 버그, 개발, 리팩토링

#62 Feat/register
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/types/user.d.ts
  src/utils/api/index.ts
  src/utils/api/postConfirmVerificationCode.ts
  src/utils/api/postCreateVerificationCode.ts
  src/utils/api/postLogin.ts
  src/utils/api/postRegister.ts
  src/utils/checkRegister.ts
Labels: 💻 개발

#63 Feat: post editor 일부 구현
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/style.ts
  src/pages/Write/index.tsx
  src/pages/Write/styles.ts
Labels: 💻 개발

#64 Style: Posts 페이지 컴포넌트 정리
  src/pages/Posts/PaginationButtons/index.tsx
  src/pages/Posts/PaginationButtons/styles.ts
  src/pages/Posts/PetitionList/index.tsx
  src/pages/Posts/PetitionList/styles.ts
  src/pages/Posts/index.tsx
  src/pages/Posts/styles.ts
Labels: ⚙️ 리팩토링, 🛠 수정, 🗂 스타일

#70 Docs: 리드미에 팀원 소개, 기술 스택 추가
  README.md
Labels: 📝 문서, 🖌 비개발, 🛠 수정

#69 Feat: 메인 페이지 총 청원 개수 API 연결
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Home/MainPrecaution/styles.ts
  src/pages/Home/index.tsx
  src/pages/Register/index.tsx
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/PostEditor/styles.ts
  src/pages/Write/PrecautionModal/GuideModal.tsx
  src/pages/Write/PrecautionModal/PrincipleModal.tsx
  src/pages/Write/WritePrecaution/WritePrecaution.tsx
  src/types/posts.d.ts
  src/utils/api/getCreatePost.ts
  src/utils/api/getPostCount.ts
  src/utils/api/getRetrieveAllPost.ts
  src/utils/api/index.ts
Labels: 💻 개발

#71 Feat/posts - 모든 게시글 불러오기 API 연결
  src/components/PostEditor/PostEditor.tsx
  src/components/PostEditor/style.ts
  src/components/PrecautionModal/GuideModal.tsx
  src/components/PrecautionModal/PrincipleModal.tsx
  src/pages/Posts/PetitionList/index.tsx
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/WritePrecaution/index.tsx
  src/pages/Write/WritePrecaution/styles.ts
  src/pages/Write/index.tsx
  src/utils/api/getRetrieveAllPost.ts
  src/utils/api/postCreatePost.ts
Labels: 💻 개발, 🥈 우선순위 - 중간, 🎮 기능

#74 feat: 회원가입 페이지 API 연결
  src/components/NavBar/NavBar.tsx
  src/pages/Login/index.tsx
  src/pages/Register/index.tsx
  src/pages/Write/PostEditor/index.tsx
  src/utils/api/index.ts
  src/utils/api/postConfirmVerificationCode.ts
  src/utils/api/postCreatePost.ts
  src/utils/api/postCreateVerificationCode.ts
  src/utils/api/postRegister.ts
  src/utils/checkRegister.ts
Labels: 👿 버그, 💻 개발

#75 Chore: 모달 잘림 해결 및 코드 정리
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Write/PrecautionModal/GuideModal.tsx
  src/pages/Write/PrecautionModal/PrincipleModal.tsx
  src/pages/Write/WritePrecaution/index.tsx
Labels: 💻 개발, ⚙️ 리팩토링, 🎨 디자인

#77 refact: 라우터 로직 일부 수정
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/pages/Login/index.tsx
  src/route/MainRouter.tsx
  src/route/PrivateRouter.tsx
  src/route/RootRouter.tsx
Labels: 💻 개발, ⚙️ 리팩토링, 🎮 기능

#81 feat: reduxjs-toolkit-persist 도입
  package.json
  src/index.tsx
  src/redux/store.ts
  yarn.lock
Labels: 💻 개발, 🚨 중요!!!, 🎮 기능

#83 함수 컴포넌트의 코드 스타일을 화살표 함수로 통일합니다
  src/pages/Home/MainPrecaution/index.tsx
  src/pages/Post/CommentForm/index.tsx
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/PetitionContents/index.tsx
  src/pages/Post/index.tsx
  src/pages/Posts/PaginationButtons/index.tsx
  src/pages/Posts/PetitionList/index.tsx
  src/pages/Write/PrecautionModal/GuideModal.tsx
  src/pages/Write/WritePrecaution/index.tsx
  src/types/post.d.ts
  src/utils/api/index.ts
  src/utils/api/post/getPostCount.ts
  src/utils/api/post/getRetrieveAllPost.ts
  src/utils/api/post/getRetrievePost.ts
  src/utils/api/post/postCreatePost.ts
  src/utils/api/user/getUsersMe.ts
  src/utils/api/user/postLogin.ts
  src/utils/api/user/postLogout.ts
  src/utils/api/user/postRegister.ts
  src/utils/api/verification/postConfirmVerificationCode.ts
  src/utils/api/verification/postCreateVerificationCode.ts
Labels: 🛠 수정, 🗂 스타일

#84 Post 페이지 청원 내용 불러오기 API 연결합니다
  package-lock.json
  package.json
  src/pages/Post/CommentForm/index.tsx
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/PetitionContents/index.tsx
  src/pages/Post/index.tsx
  src/pages/Posts/posts.json
  src/types/post.d.ts
  yarn.lock
Labels: 💻 개발, 🥇 우선순위 - 높음!!, 🛠 수정, 🎮 기능

#88 feat: query를 redux로 관리하여 페이지네이션 구현 준비
  src/pages/Posts/PaginationButtons/index.tsx
  src/pages/Posts/PetitionList/index.tsx
  src/redux/query/querySlice.ts
  src/redux/store.ts
  src/route/RootRouter.tsx
  src/utils/api/posts/getQueryPosts.ts
Labels: 💻 개발, 🥇 우선순위 - 높음!!, 🚨 중요!!!, 🎮 기능

#87 동의하기, 댓글 등록, 불러오기 API를 연결합니다.
  src/pages/Post/CommentForm/index.tsx
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/PetitionContents/index.tsx
  src/types/comment.d.ts
  src/utils/api/comment/getComments.ts
  src/utils/api/comment/postCreateComment.ts
  src/utils/api/index.ts
Labels: 💻 개발, 🥇 우선순위 - 높음!!, 🎮 기능

#90 yyyy-mm-dd 시간 형식, 댓글 등록 시간 표시, 글 출력시에도 개행 표시
  .github/CODEOWNERS
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/CommentList/styles.ts
  src/pages/Post/PetitionContents/index.tsx
  src/pages/Posts/PetitionList/index.tsx
Labels: 💻 개발, 🥉 우선순위 - 낮음, 🛠 수정

#91 feat: pagination 구현 사전 준비 완료
  src/pages/Posts/PaginationButtons/index.tsx
  src/pages/Posts/PetitionList/index.tsx
  src/types/enums.ts
  src/types/query.d.ts
Labels: 🎮 기능

#94 feat: 인증코드를 대문자로 치환하여 저장하고 표시
  src/pages/Register/index.tsx
Labels: 🛠 수정, 🎮 기능

#98 fix: 카테고리 및 페이지네이션 관련하여 수정사항 반영
  src/App.tsx
  src/pages/Home/index.tsx
  src/pages/Posts/PaginationButtons/index.tsx
  src/pages/Posts/PetitionList/index.tsx
  src/pages/Write/PostEditor/index.tsx
  src/redux/query/querySlice.ts
  src/types/enums.ts
  src/types/posts.d.ts
  src/types/query.d.ts
  src/utils/api/posts/getQueryPosts.ts
Labels: 👿 버그, 💻 개발, 🚨 중요!!!, 🛠 수정

#99 feat: 비로그인 유저 모달창 로그인 안내 (동의 하기, 의견 등록)
  src/App.tsx
  src/components/Footer/index.tsx
  src/components/NavBar/index.tsx
  src/components/NavBar/styles.ts
  src/components/NeedLoginModal/index.tsx
  src/pages/Post/CommentForm/index.tsx
  src/pages/Post/PetitionContents/index.tsx
  src/types/user.d.ts
Labels: 💻 개발, 🎨 디자인, 🎮 기능

#107 design: Write 페이지 버튼 수정
  src/pages/Home/styles.ts
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/PostEditor/styles.ts
  src/pages/Write/PrecautionModal/index.tsx
  src/pages/Write/index.tsx
Labels: 🎨 디자인

#108 feat: 페이지네이션 버튼 구현
  src/pages/Posts/PaginationButtons/index.tsx
Labels: 💻 개발, 🥈 우선순위 - 중간, 🎮 기능

#109 로그인 안내 모달창 정 가운데 배치 및 Write 페이지 css 코드 스타일 컨벤션에 맞추기 등..
  src/assets/img/logo_example.png
  src/components/NeedLoginModal/index.tsx
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/PetitionContents/styles.ts
  src/pages/Write/PostEditor/index.tsx
  src/pages/Write/PostEditor/styles.ts
  src/pages/Write/PrecautionModal/index.tsx
  src/pages/Write/PrecautionModal/steps.json
  src/pages/Write/PrecautionModal/styles.ts
  src/pages/Write/WritePrecaution/WritePrecaution.tsx
  src/pages/Write/WritePrecaution/index.tsx
  src/pages/Write/WritePrecaution/styles.ts
  src/pages/Write/index.tsx
  src/pages/Write/styles.ts
Labels: ⚙️ 리팩토링, 🎨 디자인, 🗂 스타일

#112 style: 반복되는 css속성값 전역변수화, px에서 rem/em으로 수정
  src/App.tsx
  src/components/NavBar/styles.ts
  src/pages/Home/MainPrecaution/styles.ts
  src/pages/Home/styles.ts
  src/pages/Login/styles.ts
  src/pages/Post/CommentForm/styles.ts
  src/pages/Post/CommentList/styles.ts
  src/pages/Post/PetitionContents/styles.ts
  src/pages/Post/styles.ts
  src/pages/Posts/PaginationButtons/styles.ts
  src/pages/Posts/styles.ts
  src/pages/Register/index.tsx
  src/pages/Register/styles.ts
  src/style/theme.ts
  yarn.lock
Labels: 🥇 우선순위 - 높음!!, 🎨 디자인, 🛠 수정

#114 페이지네이션 세퍼레이터 UI 변경
  src/pages/Posts/PaginationButtons/index.tsx
Labels: 🎨 디자인, 🛠 수정

#115 fix: 개행 및 issue 110 해결(#110)
  package-lock.json
  package.json
  src/pages/Post/CommentList/index.tsx
  src/pages/Post/CommentList/styles.ts
  src/pages/Post/PetitionContents/index.tsx
  src/pages/Post/PetitionContents/styles.ts
  yarn.lock
Labels: 👿 버그
